config/routes.rb
Todos::Application.routes.draw do
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
  resources :user_sessions
  

  resources :todos do
    member do
      get 'cambiar_estado'
    end
    collection do
    end
  end

  root :to => 'user_sessions#new'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :descripcion
  
  validates :descripcion, :presence => true
  validates :user_id, :presence => true

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body

  has_many :todos
  
  validates :name, :presence => true

end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/todos_controller.rb
# encoding: utf-8
class TodosController < ApplicationController
  
  before_filter :require_login

  def index
    @new_todo ||= Todo.new
    @todos = current_user.todos.order("id DESC")
  end
  
  def create
    @new_todo = Todo.new params[:todo]
    @new_todo.user = current_user
    if @new_todo.save
      respond_to do |format|
        format.html {
          flash["alert-success"] = "Guardado."
          redirect_to action: :index
        }
        format.js
      end
    else
      respond_to do |format|
        format.html {
          flash["alert-error"] = "Hubo un problema."
          render :index
        }
        format.js
      end
    end
  end
  
  def cambiar_estado
    if @todo = current_user.todos.find_by_id(params[:id])
      if @todo.completado
        @todo.completado = false
      else
        @todo.completado = true
      end
      @todo.save
      render :text => "#{@todo.completado}"
    else
      render :text => "estás haciendo travesuras?"
    end
  end
  
  def destroy
    if @todo = current_user.todos.find_by_id(params[:id])
      @todo.destroy
      respond_to do |format|
        format.js {
          render :text => "Ok"
        }
      end
    else
      render :text => "¿Sigues haciendo travesuras?"
    end
  end
  
end

app/controllers/user_sessions_controller.rb
# encoding: utf-8
class UserSessionsController < ApplicationController
  
  def new
    if current_user
      redirect_to :controller => :todos, :action => :index
    end
  end
  
  def create
    if @user = login(params[:username], params[:password])
      session[:user_id] = @user.id
      flash["alert-success"] = "Has iniciado sesión"
      redirect_to root_path
    else
      flash["alert-error"] = "Nombre de usuario o contraseña inválidos"
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash["alert-notice"] = "Cerraste sesión"
    redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/_logged_in.html.erb
<% if current_user %>
  Iniciaste sesión como <%= current_user.name %>. <%= link_to "cerrar sesión", logout_path %>
<% else %>
  <%= link_to "inicia sesión", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <meta name="viewport" content="minimum-scale=1.0, width=device-width, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <header>
    <h1>
      Por hacer
    </h1>
    <div id="alerts">
      <% flash.each do |key, value| %>
        <div class='<%= key %>'>
          <%= value %>
          <span class='close_alert'>
            X
          </span>
        </div>
      <% end %>
    </div>
    <div id="current_user">
      <%= render 'layouts/logged_in' %>
    </div>
  </header>
  <div id="container">
    <%= yield %>
  </div>
  <footer>
    
  </footer>

</body>
</html>

app/views/todos/_todo.html.erb
<div class="todo" data-todo_id="<%= todo.id %>">
  <span>
    <%= todo.descripcion %>
  </span>
  <input type="checkbox" class="todo_checkbox" <%= todo.completado ? "checked='checked'" : '' %>>
  <button class="eliminar_todo">eliminar</button>
</div>

app/views/todos/create.js.erb
<% if @new_todo.new_record? %>
  window.Helpers.Notification.create("alert-error","Hubo un problema.");
<% else %>
  $(".todos_los_todos").prepend("<%= j render('todo', todo: @new_todo) %>");
  $("#todo_descripcion").val("");
    window.Helpers.Notification.create("alert-success","Tienes algo más que hacer.");
<% end %>

app/views/todos/index.html.erb
<div class="todos_los_todos">
  <% @todos.each do |todo| %>
    <%= render 'todo', todo: todo %>
  <% end %>
</div>

<%= form_for @new_todo, :remote => true do |f| %>
  <%= f.text_field :descripcion, :class => "new_todo_input", :required => true %>
<% end %>

<%= #javascript_tag "TodosController.init()"
%>

app/views/user_sessions/new.html.erb
<%= form_tag user_sessions_path do %>
  <%= text_field_tag :username, params[:username], :placeholder => "Nombre de usuario", :required => true %>
  <%= password_field_tag :password, "", :placeholder => "Contraseña" %>
  <%= submit_tag "Iniciar sesión", :disable_with => "Entrando..", :required => true %>
<% end %>